const TOKEN = /\{\{\s*([\w.-]+)\s*\}\}/g;

/** 把文本里的 `{{ key }}` 替换为变量值；未知变量原样保留，便于暴露模板笔误。 */
export function render(input: string, variables: Record<string, string>): string {
  return input.replace(TOKEN, (match, key: string) => variables[key] ?? match);
}

/** 把 `/` 分隔的相对路径逐段渲染。 */
export function renderPath(relPath: string, variables: Record<string, string>): string {
  return relPath
    .split("/")
    .map((segment) => render(segment, variables))
    .join("/");
}

/** 转成合法的 npm 包名。 */
export function toPackageName(raw: string): string {
  const cleaned = raw
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-~._]+/g, "-")
    .replace(/^[._-]+/, "")
    .replace(/[._-]+$/, "")
    .replace(/-{2,}/g, "-");
  return cleaned.length > 0 ? cleaned : "my-app";
}

/** 转成人类可读标题。 */
export function toTitle(raw: string): string {
  return raw
    .replace(/[-_]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

/** 模板渲染时始终可用的内置变量。 */
export function defaultVariables(
  projectName: string,
  options: { description?: string; author?: string } = {},
): Record<string, string> {
  const name = toPackageName(projectName);
  return {
    name,
    projectName,
    title: toTitle(projectName),
    description: options.description ?? "A project generated by @excellence-wh/cz.",
    author: options.author ?? "",
    year: String(new Date().getFullYear()),
  };
}
